config/routes.rb
Rails.application.routes.draw do
  get 'book_comments/create'
  get 'book_comments/destroy'
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about", as:'about'
  
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
   
  resources :users, only: [:show, :edit, :index, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :user_id, uniqueness: {scope: :book_id}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}
  
  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def get_profile_image(width, height)
   file_path = Rails.root.join('app/assets/images/default-image.jpg')

    unless profile_image.attached?
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.find_by(book_id: book.id)
    comment.destroy
    redirect_back(fallback_location: root_path)
  end
  

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @book2= Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    if @user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      @user =@book.user
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User was successfully updated."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.html.erb
<h1>BookComments#create</h1>
<p>Find me in app/views/book_comments/create.html.erb</p>

app/views/book_comments/destroy.html.erb
<h1>BookComments#destroy</h1>
<p>Find me in app/views/book_comments/destroy.html.erb</p>

app/views/books/_new.html.erb
<h2 class="mt-3">New book</h2>
<% if book.errors.any? %>
  <ul class="alert alert-danger" role="alert">
    <h6 class="alert-heading">
      <%= book.errors.count %>件のエラーが発生しました
    </h6>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: book, url: "/books", method: "post") do |form| %>

  <div class="form-group">
    <%= form.label :title, "Title" %>
    <%= form.text_field :title, class: "form-control book_title", id: "book_title" %>
  </div>

  <div class="form-group">
    <%= form.label :body, "Opinion" %>
    <%= form.text_area :body, class: "form-control book_body", id: "book_body" %>
  </div>

  <div class="form-group">
    <%= form.submit "Create Book", class: "btn btn-success", data: { disable_with: "Create Book" } %>
  </div>
<% end %>

app/views/books/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <%= @book.errors.count %> error prohibited this obj from being saved: %>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @book do |form| %>
          <div class="form-group">
            <%= form.label :title, "Title" %>
            <%= form.text_field :title, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= form.label :body, "Opinion" %>
            <%= form.text_area :body, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= form.submit "Update Book", class: "btn btn-success" %>
          </div>
        <% end %>
        <%= link_to "Show", book_path(@book.id) %> |
        <a class="back" href="/books">Back</a>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'new', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(book.id) do %>
                <%= image_tag book.user.get_profile_image(100, 100) %>
              <% end %>
            </td>
            <td>
              <%= link_to book.title, book_path(book) %>
            </td>
            <td><%= book.body %></td>
            <td>
              <% if book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    <i class="fas fa-heart" style="color: red;"></i>
                    <span style="color: red;"><%= book.favorites.count %></span>
                  <% end %>
                </p>
              <% else %>
                <p>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <i class="fas fa-heart"></i>
                    <%= book.favorites.count %>
                  <% end %>
                </p>
              <% end %>
            </td>
            <td>
              <p>コメント数：<%= book.book_comments.count %></p>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'new', book: @book2 %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= image_tag @user.get_profile_image(100, 100) %><br>
              <%= link_to @user.name, user_path(@user.id) %>
            </td>
            <% if @book.user == current_user %>
              <td><%= link_to @book.title, book_path(@book.id) %></td>
              <td><%= @book.body %></td>
              <td>
                <%= link_to edit_book_path(@book.id) do %>
                  <i class="btn btn-sm btn-success">Edit</i>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？" do %>
                  <i class="btn btn-sm btn-danger">Destroy</i>
                <% end %>
              </td>
            <% else %>
              <td><%= link_to @book.title, book_path(@book.id) %></td>
              <td><%= @book.body %></td>
            <% end %>
            <td>
             <% if @book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(@book), method: :delete do %>
                    <i class="fas fa-heart" style="color: red;"></i>
                    <span style="color: red;"><%= @book.favorites.count %></span>
                  <% end %>
                </p>
              <% else %>
                <p>
                  <%= link_to book_favorites_path(@book), method: :post do %>
                    <i class="fas fa-heart"></i>
                    <%= @book.favorites.count %> 
                  <% end %>
                </p>
              <% end %>
            </td>
            <td>
              <p>コメント数：<%= @book.book_comments.count %></p>
            </td>
          </tr>
         　 <% @book.book_comments.each do |book_comment| %>
            <tr>
              <td>
                <%= image_tag book_comment.user.get_profile_image(100, 100) %><br> 
                <%= link_to book_comment.user.name, user_path(book_comment.user.id) %>
              </td>
              <td><%= book_comment.comment %></td>
              <td>
                <% if book_comment.user == current_user %>
                  <%= link_to book_book_comment_path(@book.id, book_comment.id), method: :delete do %>
                    <i class="btn btn-sm btn-danger">Destroy</i>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>

        </tbody>
      </table>
      
      <div>
        <%= form_with model: [@book, @book_comment] do |f| %>
          <%= f.text_area :comment, rows: '5' %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i> <strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i> <strong>Bookers</strong> !!</h1>
        <p>In <i class="fas fa-book"></i> <strong>Bookers</strong>,</p>
        <p>you can share and exchange your opinions, impressions, and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/a8ac2bccea.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <div class="navbar-brand p-3"><%= link_to "Bookers", root_path, class: 'nav-link text-light' %></div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-users"></i> Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-book-open"></i> Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-out-alt"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-link"></i> About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-in-alt"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <div>
         <%= flash[:notice] %>
      </div>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
      	<div class="row">
        	<div class="mx-auto">
        		<p>CopyRight Infratop.inc</p>
        	</div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/_info.html.erb
<h2>User info</h2>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <%= image_tag user.get_profile_image(100, 100) %>
  </tbody>
</table>


<%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
  <i class="fas fa-user-cog"></i>
<% end %>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>

        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this record from being saved:</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= form_with(model: @user, local: true) do |form| %>

          <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :Image %>
            <%= form.file_field :profile_image, class: 'form-control-file', accept: 'image/*' %>
          </div>

          <div class="form-group">
            <%= form.label :introduction %>
            <%= form.text_area :introduction, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.submit "Update User", class: 'btn btn-secondary', data: { disable_with: "Updating..." } %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'info', user: @user %>
      <%= render 'books/new', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td><%= image_tag user.get_profile_image(100, 100) %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'info', user: @user %>
      <%= render 'books/new', book: @book %>
    </div>
    
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= image_tag @user.get_profile_image(100, 100) %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
            <td>
              <% if book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    <i class="fas fa-heart" style="color: red;"></i>
                    <span style="color: red;"><%= book.favorites.count %></span>
                  <% end %>
                </p>
              <% else %>
                <p>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <i class="fas fa-heart"></i>
                    <%= book.favorites.count %> 
                  <% end %>
                </p>
              <% end %>
            </td>
            <td>
              <p>コメント数：<%= book.book_comments.count %></p>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>